This repo has  preprocessing samples using nltk library and below is my learnings from this sample

1) Stop words removal has to be added if decoding text is not needed
2) Corpus is built from training data (No pretrained models are used in this sample)
3) Preprocessing activities attempted here
    Stemming (Brute force approach) so evaluvated LancasterStemmer and WordNetLemmatizer
    Used PoS Tags
5) Frequency filtering
4) How to fit_transform to Vectorembedding TF-IDF (filtered out most frequently used words as most frequently used words were assumed as stop words)


In [ ]:
from urllib.request import urlopen
from bs4 import BeautifulSoup  

In [5]:
articleURL = "https://www.washingtonpost.com/news/the-switch/wp/2016/10/18/the-pentagons-massive-new-telescope-is-designed-to-track-space-junk-and-watch-out-for-killer-asteroids/"

In [6]:
page = urlopen(articleURL).read().decode('utf8','ignore') 
soup = BeautifulSoup(page,"lxml")


In [7]:
soup.find('article')

<article class="grid-article mb-xxl-ns" data-qa="main"><div data-qa="lede-art" data-testid="lede-art"><div><figure class="mb-md mr-auto-ns ml-auto-ns hide-for-print ml-neg-gutter mr-neg-gutter"><div class="w-100 aspect-custom" style="background-position:center;background-repeat:no-repeat;background-color:rgb(245, 245, 245);background-image:url(https://www.washingtonpost.com/wp-apps/imrs.php?src=https%3A%2F%2Fd1i4t8bqe7zgj6.cloudfront.net%2F10-18-2016%2Ft_1476804667714_name_20161018_DarpaPic.jpg&amp;w=960);background-size:contain;--aspect-height:0.5625;--aspect-width:1;filter:blur(5px);transition:filter .1s"></div><figcaption><div class="mt-xs mr-auto-ns ml-auto-ns left font--subhead font-xxxs gray-dark ml-gutter mr-gutter" data-qa="video-caption">The Space Surveillance Telescope offers improvements in determining the orbits of newly discovered objects and provides rapid observations of space events. (Video: DARPAtv)</div></figcaption></figure></div></div><div class="grid-body"><div cla

In [8]:
soup.find('article').text

"The Space Surveillance Telescope offers improvements in determining the orbits of newly discovered objects and provides rapid observations of space events. (Video: DARPAtv)Gift ArticleShareThere are a lot of rocks flying around through space. Lots of debris, too. Old satellites, spent rocket boosters, even for a short while a spatula that got loose during a space shuttle mission in 2006. All of it swirling around in orbit, creating a bit of a traffic jam.Tech is not your friend. We are. Sign up for The Tech Friend newsletter.ArrowRightFor years, the Pentagon has been worried about the collisions that might be caused by an\xa0estimated 500,000 pieces of debris, taking out enormously valuable satellites and, in turn, creating even more debris. On Tuesday, the Defense Department\xa0took another significant step toward monitoring all of the cosmic junk swirling around in space, by delivering\xa0a gigantic new telescope capable of seeing small objects from very far away.Developed by the De

In [9]:
text = ' '.join(map(lambda p: p.text, soup.find_all('article')))
text

"The Space Surveillance Telescope offers improvements in determining the orbits of newly discovered objects and provides rapid observations of space events. (Video: DARPAtv)Gift ArticleShareThere are a lot of rocks flying around through space. Lots of debris, too. Old satellites, spent rocket boosters, even for a short while a spatula that got loose during a space shuttle mission in 2006. All of it swirling around in orbit, creating a bit of a traffic jam.Tech is not your friend. We are. Sign up for The Tech Friend newsletter.ArrowRightFor years, the Pentagon has been worried about the collisions that might be caused by an\xa0estimated 500,000 pieces of debris, taking out enormously valuable satellites and, in turn, creating even more debris. On Tuesday, the Defense Department\xa0took another significant step toward monitoring all of the cosmic junk swirling around in space, by delivering\xa0a gigantic new telescope capable of seeing small objects from very far away.Developed by the De

In [10]:
text = text.replace("?"," ")
text.encode('ascii', errors='replace')
print(text)

The Space Surveillance Telescope offers improvements in determining the orbits of newly discovered objects and provides rapid observations of space events. (Video: DARPAtv)Gift ArticleShareThere are a lot of rocks flying around through space. Lots of debris, too. Old satellites, spent rocket boosters, even for a short while a spatula that got loose during a space shuttle mission in 2006. All of it swirling around in orbit, creating a bit of a traffic jam.Tech is not your friend. We are. Sign up for The Tech Friend newsletter.ArrowRightFor years, the Pentagon has been worried about the collisions that might be caused by an estimated 500,000 pieces of debris, taking out enormously valuable satellites and, in turn, creating even more debris. On Tuesday, the Defense Department took another significant step toward monitoring all of the cosmic junk swirling around in space, by delivering a gigantic new telescope capable of seeing small objects from very far away.Developed by the Defense Adva

In [11]:
def getTextWaPo(url):
    page = urlopen(url).read().decode('utf8')
    soup = BeautifulSoup(page,"lxml")
    text = ' '.join(map(lambda p: p.text, soup.find_all('article')))
    text = text.replace("?"," ")
    return text.encode('ascii', errors='replace')

In [12]:
text = getTextWaPo(articleURL)

In [13]:
print(type(text))
text = str(text, 'UTF-8')
print(type(text))

<class 'bytes'>
<class 'str'>


In [16]:
text

"The Space Surveillance Telescope offers improvements in determining the orbits of newly discovered objects and provides rapid observations of space events. (Video: DARPAtv)Gift ArticleShareThere are a lot of rocks flying around through space. Lots of debris, too. Old satellites, spent rocket boosters, even for a short while a spatula that got loose during a space shuttle mission in 2006. All of it swirling around in orbit, creating a bit of a traffic jam.Tech is not your friend. We are. Sign up for The Tech Friend newsletter.ArrowRightFor years, the Pentagon has been worried about the collisions that might be caused by an?estimated 500,000 pieces of debris, taking out enormously valuable satellites and, in turn, creating even more debris. On Tuesday, the Defense Department?took another significant step toward monitoring all of the cosmic junk swirling around in space, by delivering?a gigantic new telescope capable of seeing small objects from very far away.Developed by the Defense Adv

In [14]:
from nltk.tokenize import sent_tokenize,word_tokenize
from nltk.corpus import stopwords
from string import punctuation

In [15]:
sents = sent_tokenize(text)
sents

['The Space Surveillance Telescope offers improvements in determining the orbits of newly discovered objects and provides rapid observations of space events.',
 '(Video: DARPAtv)Gift ArticleShareThere are a lot of rocks flying around through space.',
 'Lots of debris, too.',
 'Old satellites, spent rocket boosters, even for a short while a spatula that got loose during a space shuttle mission in 2006.',
 'All of it swirling around in orbit, creating a bit of a traffic jam.Tech is not your friend.',
 'We are.',
 'Sign up for The Tech Friend newsletter.ArrowRightFor years, the Pentagon has been worried about the collisions that might be caused by an?estimated 500,000 pieces of debris, taking out enormously valuable satellites and, in turn, creating even more debris.',
 'On Tuesday, the Defense Department?took another significant step toward monitoring all of the cosmic junk swirling around in space, by delivering?a gigantic new telescope capable of seeing small objects from very far away

In [18]:
word_sent = word_tokenize(text.lower())
word_sent

['the',
 'space',
 'surveillance',
 'telescope',
 'offers',
 'improvements',
 'in',
 'determining',
 'the',
 'orbits',
 'of',
 'newly',
 'discovered',
 'objects',
 'and',
 'provides',
 'rapid',
 'observations',
 'of',
 'space',
 'events',
 '.',
 '(',
 'video',
 ':',
 'darpatv',
 ')',
 'gift',
 'articlesharethere',
 'are',
 'a',
 'lot',
 'of',
 'rocks',
 'flying',
 'around',
 'through',
 'space',
 '.',
 'lots',
 'of',
 'debris',
 ',',
 'too',
 '.',
 'old',
 'satellites',
 ',',
 'spent',
 'rocket',
 'boosters',
 ',',
 'even',
 'for',
 'a',
 'short',
 'while',
 'a',
 'spatula',
 'that',
 'got',
 'loose',
 'during',
 'a',
 'space',
 'shuttle',
 'mission',
 'in',
 '2006.',
 'all',
 'of',
 'it',
 'swirling',
 'around',
 'in',
 'orbit',
 ',',
 'creating',
 'a',
 'bit',
 'of',
 'a',
 'traffic',
 'jam.tech',
 'is',
 'not',
 'your',
 'friend',
 '.',
 'we',
 'are',
 '.',
 'sign',
 'up',
 'for',
 'the',
 'tech',
 'friend',
 'newsletter.arrowrightfor',
 'years',
 ',',
 'the',
 'pentagon',
 'has',
 

In [19]:
print(len(word_sent))

829


In [20]:
_stopwords = set(stopwords.words('english') + list(punctuation))
_stopwords

{'!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'did',
 'do',
 'does',
 'doing',
 'don',
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'has',
 'have',
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'it',
 'its',
 'itself',
 'just',
 'me',
 'more',
 'most',
 'my',
 'myself',
 'no',
 'nor',
 'not',
 'now',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 's',
 'same',
 'she',
 'should',
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 'the',
 'their',
 'theirs',
 'them',
 'them

In [21]:
word_sent=[word for word in word_sent if word not in _stopwords]

In [22]:
print(len(word_sent))

425


In [23]:
word_sent

['space',
 'surveillance',
 'telescope',
 'offers',
 'improvements',
 'determining',
 'orbits',
 'newly',
 'discovered',
 'objects',
 'provides',
 'rapid',
 'observations',
 'space',
 'events',
 'video',
 'darpatv',
 'gift',
 'articlesharethere',
 'lot',
 'rocks',
 'flying',
 'around',
 'space',
 'lots',
 'debris',
 'old',
 'satellites',
 'spent',
 'rocket',
 'boosters',
 'even',
 'short',
 'spatula',
 'got',
 'loose',
 'space',
 'shuttle',
 'mission',
 '2006.',
 'swirling',
 'around',
 'orbit',
 'creating',
 'bit',
 'traffic',
 'jam.tech',
 'friend',
 'sign',
 'tech',
 'friend',
 'newsletter.arrowrightfor',
 'years',
 'pentagon',
 'worried',
 'collisions',
 'might',
 'caused',
 'estimated',
 '500,000',
 'pieces',
 'debris',
 'taking',
 'enormously',
 'valuable',
 'satellites',
 'turn',
 'creating',
 'even',
 'debris',
 'tuesday',
 'defense',
 'department',
 'took',
 'another',
 'significant',
 'step',
 'toward',
 'monitoring',
 'cosmic',
 'junk',
 'swirling',
 'around',
 'space',
 'de

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()

In [27]:
count_vectorizer.fit_transform(sents)

<27x362 sparse matrix of type '<class 'numpy.int64'>'
	with 622 stored elements in Compressed Sparse Row format>

In [29]:
count_vectorizer.get_feature_names_out()

array(['000', '10', '17', '2006', '2007', '22', '500', '90', 'ability',
       'about', 'advanced', 'advertisementover', 'advertisementthe',
       'advertisementwith', 'advisor', 'agency', 'air', 'all', 'allow',
       'allows', 'also', 'america', 'amount', 'an', 'and', 'another',
       'are', 'area', 'areas', 'around', 'arrowrightfor',
       'articleloading', 'articlesharethere', 'as', 'asia', 'assets',
       'asteroids', 'at', 'atoll', 'australia', 'awareness', 'away',
       'base', 'based', 'be', 'because', 'become', 'been', 'being',
       'benign', 'best', 'bethesda', 'big', 'bit', 'blew', 'boosters',
       'brian', 'built', 'but', 'by', 'calls', 'can', 'capability',
       'capable', 'cause', 'caused', 'ceremony', 'chinese', 'closely',
       'cognizant', 'collide', 'collisions', 'command', 'commander',
       'communications', 'competitive', 'concerned', 'congested',
       'contested', 'cosmic', 'could', 'creating', 'critical',
       'critically', 'currently', 'damage', 

In [30]:
count_vectorizer.vocabulary_

{'the': 301,
 'space': 278,
 'surveillance': 284,
 'telescope': 295,
 'offers': 211,
 'improvements': 148,
 'in': 149,
 'determining': 96,
 'orbits': 221,
 'of': 210,
 'newly': 201,
 'discovered': 99,
 'objects': 207,
 'and': 24,
 'provides': 242,
 'rapid': 244,
 'observations': 208,
 'events': 111,
 'video': 335,
 'darpatv': 87,
 'gift': 132,
 'articlesharethere': 32,
 'are': 26,
 'lot': 174,
 'rocks': 253,
 'flying': 121,
 'around': 29,
 'through': 308,
 'lots': 175,
 'debris': 89,
 'too': 314,
 'old': 213,
 'satellites': 257,
 'spent': 280,
 'rocket': 252,
 'boosters': 55,
 'even': 110,
 'for': 122,
 'short': 267,
 'while': 349,
 'spatula': 279,
 'that': 300,
 'got': 138,
 'loose': 173,
 'during': 101,
 'shuttle': 268,
 'mission': 189,
 '2006': 3,
 'all': 17,
 'it': 158,
 'swirling': 287,
 'orbit': 220,
 'creating': 81,
 'bit': 53,
 'traffic': 319,
 'jam': 160,
 'tech': 292,
 'is': 156,
 'not': 205,
 'your': 361,
 'friend': 126,
 'we': 341,
 'sign': 269,
 'up': 327,
 'newsletter': 2

In [32]:
count_vectorizer.vocabulary_.get('events')

111

In [38]:
frequency_term_matrix = count_vectorizer.transform(sents)

In [39]:
print(frequency_term_matrix.shape)

(27, 362)


In [40]:
print(frequency_term_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
#Totally new data when not present in corpus output is zeros
test_text = ["Every cloud has a silver lining."]

count_vectorizer.transform(test_text).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [37]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()

In [42]:
tfidf_vector1 = tfidf_transformer.fit_transform(frequency_term_matrix)

tfidf_vector1.shape

(27, 362)

In [43]:
tfidf_vector1.toarray()

array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.235666, 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ]])

In [44]:
print(tfidf_vector1.toarray())

[[0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]
 ...
 [0.       0.       0.       ... 0.235666 0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.       0.       0.      ]]


In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

In [52]:
tfidf_vector2 = tfidf_vectorizer.fit_transform(sents)

tfidf_vectorizer.vocabulary_

{'the': 301,
 'space': 278,
 'surveillance': 284,
 'telescope': 295,
 'offers': 211,
 'improvements': 148,
 'in': 149,
 'determining': 96,
 'orbits': 221,
 'of': 210,
 'newly': 201,
 'discovered': 99,
 'objects': 207,
 'and': 24,
 'provides': 242,
 'rapid': 244,
 'observations': 208,
 'events': 111,
 'video': 335,
 'darpatv': 87,
 'gift': 132,
 'articlesharethere': 32,
 'are': 26,
 'lot': 174,
 'rocks': 253,
 'flying': 121,
 'around': 29,
 'through': 308,
 'lots': 175,
 'debris': 89,
 'too': 314,
 'old': 213,
 'satellites': 257,
 'spent': 280,
 'rocket': 252,
 'boosters': 55,
 'even': 110,
 'for': 122,
 'short': 267,
 'while': 349,
 'spatula': 279,
 'that': 300,
 'got': 138,
 'loose': 173,
 'during': 101,
 'shuttle': 268,
 'mission': 189,
 '2006': 3,
 'all': 17,
 'it': 158,
 'swirling': 287,
 'orbit': 220,
 'creating': 81,
 'bit': 53,
 'traffic': 319,
 'jam': 160,
 'tech': 292,
 'is': 156,
 'not': 205,
 'your': 361,
 'friend': 126,
 'we': 341,
 'sign': 269,
 'up': 327,
 'newsletter': 2

In [53]:
tfidf_vector2.shape

(27, 362)

In [55]:
dict(zip(tfidf_vectorizer.get_feature_names_out(), tfidf_vectorizer.idf_))

{'000': 2.9459101490553135,
 '10': 3.2335922215070942,
 '17': 3.6390573296152584,
 '2006': 3.6390573296152584,
 '2007': 3.6390573296152584,
 '22': 3.6390573296152584,
 '500': 3.2335922215070942,
 '90': 3.6390573296152584,
 'ability': 3.6390573296152584,
 'about': 2.9459101490553135,
 'advanced': 3.2335922215070942,
 'advertisementover': 3.6390573296152584,
 'advertisementthe': 3.6390573296152584,
 'advertisementwith': 3.6390573296152584,
 'advisor': 3.6390573296152584,
 'agency': 3.2335922215070942,
 'air': 2.540445040947149,
 'all': 3.2335922215070942,
 'allow': 3.2335922215070942,
 'allows': 3.6390573296152584,
 'also': 3.6390573296152584,
 'america': 3.6390573296152584,
 'amount': 3.6390573296152584,
 'an': 2.7227665977411037,
 'and': 2.1349799328389842,
 'another': 2.9459101490553135,
 'are': 2.386294361119891,
 'area': 3.2335922215070942,
 'areas': 3.2335922215070942,
 'around': 2.7227665977411037,
 'arrowrightfor': 3.6390573296152584,
 'articleloading': 3.6390573296152584,
 'arti

In [56]:
tfidf_vector2.toarray()

array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [0.      , 0.      , 0.      , ..., 0.235666, 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ]])

In [59]:
count_vectorizer.inverse_transform(transformed_vector)

[array(['and', 'determining', 'discovered', 'events', 'improvements', 'in',
        'newly', 'objects', 'observations', 'of', 'offers', 'orbits',
        'provides', 'rapid', 'space', 'surveillance', 'telescope', 'the'],
       dtype='<U17'),
 array(['are', 'around', 'articlesharethere', 'darpatv', 'flying', 'gift',
        'lot', 'of', 'rocks', 'space', 'through', 'video'], dtype='<U17'),
 array(['debris', 'lots', 'of', 'too'], dtype='<U17'),
 array(['2006', 'boosters', 'during', 'even', 'for', 'got', 'in', 'loose',
        'mission', 'old', 'rocket', 'satellites', 'short', 'shuttle',
        'space', 'spatula', 'spent', 'that', 'while'], dtype='<U17'),
 array(['all', 'around', 'bit', 'creating', 'friend', 'in', 'is', 'it',
        'jam', 'not', 'of', 'orbit', 'swirling', 'tech', 'traffic', 'your'],
       dtype='<U17'),
 array(['are', 'we'], dtype='<U17'),
 array(['000', '500', 'about', 'an', 'and', 'arrowrightfor', 'be', 'been',
        'by', 'caused', 'collisions', 'creating', 'deb

### Filtering words based on frequency

In [61]:
count_vectorizer = CountVectorizer(min_df=2, max_df=100)

transformed_vector = count_vectorizer.fit_transform(sents)

transformed_vector.shape

(27, 97)

In [65]:
from nltk.stem import *

In [66]:
ls = LancasterStemmer()
ls_stemmed_tokens = []
newsents=[]
for sent in sents:
    newword=[]
    for word in word_tokenize(sent.lower()):
        newword.append(ls.stem(word))
    newsents.append(" ".join(newword))

In [67]:
newsents

['the spac surveil telescop off improv in determin the orbit of new discov object and provid rapid observ of spac ev .',
 '( video : darpatv ) gift articleshareth ar a lot of rock fly around through spac .',
 'lot of debr , too .',
 'old satellit , spent rocket boost , ev for a short whil a spatul that got loos dur a spac shuttl miss in 2006 .',
 'al of it swirl around in orbit , cre a bit of a traff jam.tech is not yo friend .',
 'we ar .',
 'sign up for the tech friend newsletter.arrowrightf year , the pentagon has been worry about the collid that might be caus by an ? estim 500,000 piec of debr , tak out enorm valu satellit and , in turn , cre ev mor debr .',
 'on tuesday , the defens depart ? took anoth sign step toward monit al of the cosm junk swirl around in spac , by del ? a gig new telescop cap of see smal object from very far away.developed by the defens adv research project ag , the spac surveil telescop was form transfer to the air forc dur a ceremony at whit sand missil ba

In [68]:
print(wnl.lemmatize('definitions'))

definition


In [94]:
# POS_TAGGER_FUNCTION : TYPE 1
def nltk_pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:          
        return None

 

In [96]:
from nltk.stem import WordNetLemmatizer
stop_words = set(stopwords.words('english'))
wnl = WordNetLemmatizer()
newsents=[]
for sent in sents:
    newword=[]
    words=word_tokenize(sent.lower())
    nltk_tagged = nltk.pos_tag(nltk.word_tokenize(sent))  
    wordnet_tagged = map(lambda x: (x[0], nltk_pos_tagger(x[1])), nltk_tagged)
    for word, tag in wordnet_tagged:
        if word in stop_words:
            newsents.append(word)
        else:
            if tag is None:
                # if there is no available tag, append the token as is
                newsents.append(word)
            else:       
                # else use the tag to lemmatize the token
                newsents.append(lemmatizer.lemmatize(word, tag))
    lemmatized_sentence = " ".join(newsents)

In [97]:
lemmatized_sentence

"The Space Surveillance Telescope offer improvement in determine the orbit of newly discover object and provide rapid observation of space event . ( Video : DARPAtv ) Gift ArticleShareThere are a lot of rock fly around through space . Lots of debris , too . Old satellite , spend rocket booster , even for a short while a spatula that get loose during a space shuttle mission in 2006 . All of it swirl around in orbit , create a bit of a traffic jam.Tech is not your friend . We are . Sign up for The Tech Friend newsletter.ArrowRightFor year , the Pentagon has been worry about the collision that might be cause by an ? estimate 500,000 piece of debris , take out enormously valuable satellite and , in turn , create even more debris . On Tuesday , the Defense Department ? take another significant step toward monitor all of the cosmic junk swirl around in space , by deliver ? a gigantic new telescope capable of see small object from very far away.Developed by the Defense Advanced Research Proje