<a href="https://colab.research.google.com/github/SridhanyaG/NLPBasicPreprocessingUsingNLTK/blob/main/PytorchSample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:
a = np.array([1, 2])
b = np.array([8, 9])
c = a + b
c


array([ 9, 11])

In [ ]:
a = torch.tensor([1, 2])
b = torch.tensor([8, 9])
c = a + b
c

tensor([ 9, 11])

In [ ]:
a = torch.tensor([1, 2])
a.numpy()

array([1, 2])

In [ ]:
a = np.array([1, 2])
torch.from_numpy(a)

tensor([1, 2])

In [ ]:
torch.tensor([[1, 2], [2, 1]])


tensor([[1, 2],
        [2, 1]])

In [ ]:
torch.FloatTensor([[1, 2], [2, 1]])


tensor([[1., 2.],
        [2., 1.]])

In [ ]:
torch.tensor([[1, 2], [2, 1]], dtype=torch.bool)


tensor([[True, True],
        [True, True]])

In [ ]:
torch.rand(3, 2)


tensor([[0.2310, 0.7076],
        [0.6171, 0.2010],
        [0.4638, 0.1609]])

In [ ]:
torch.ones(3, 2)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
x = torch.tensor([[2, 3], [1, 2]])
print(x)
print(f'sum: {x.sum()}')

tensor([[2, 3],
        [1, 2]])
sum: 8


In [ ]:
x.t()


tensor([[2, 1],
        [3, 2]])

In [ ]:
x.size()


torch.Size([2, 2])

In [ ]:
y = torch.tensor([[2, 2], [5, 1]])
z = x.add(y)
z

tensor([[4, 5],
        [6, 3]])

In [ ]:
x.add_(y)
x

tensor([[4, 5],
        [6, 3]])